### ISSUE TITLE
[Feature Request] Long Date format

### ISSUE THREAD

**Issue by pramitbiswas** [intika/org.kde.plasma.digitalclocklite#2]
Currently, it is:      Monday 29 April 2019
Request format:    Mo 29-04-2019

Day: {Mo, Tu, We, Th, Fr, Sa, Su}
Date: DD-MM-YYYY

{Da DD-MM-YYYY}:   This can be added as additional from the drop down list of date format in settings panel.

**Comment by intika** [comment]
Hi, thank you for your feed back :) 

This is actually a little bit out of the scope of the plasmoid because it is managed by the system, you can change the date format with other methods. 

Here is some links on how to do it: 

https://www.linuxquestions.org/questions/linuxquestions-org-member-success-stories-23/guide-to-setting-custom-date-format-in-recent-versions-of-kde-4175595458/

https://superuser.com/questions/1162283/use-iso-time-and-date-format-in-kde-5

https://unix.stackexchange.com/questions/410844/how-to-hack-and-modify-a-predefined-date-time-format-of-kde-5-that-comes-with-de

**Comment by pramitbiswas** [comment]
I followed [this](https://forum.kde.org/viewtopic.php?f=17&t=134970) ([reference](https://doc.qt.io/qt-5/qml-qtqml-date.html)).

change in `~/.local/share/plasma/plasmoids/org.kde.plasma.mydigitalclock/contents/ui/DigitalClock.qml` or `/usr/share/plasma/plasmoids/org.kde.plasma.mydigitalclock/contents/ui/DigitalClock.qml`

> return Qt.formatTime(currentTime, main.timeFormat);
to
> return Qt.formatTime(currentTime, "hh:mm");

and

> dateLabel.text = Qt.formatDate(main.currentTime, main.dateFormat);
to
> dateLabel.text = Qt.formatDate(main.currentTime, "ddd dd-MM-yy");

**Comment by intika** [comment]
Great thanks for reporting that for other users ;)
